[package]
name = "aoc-problem-fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
reqwest = { version = "0.12", features = ["blocking"] }
console = "0.15"
